# 基本となるComposeファイル (CPU環境のデフォルト)
name: takumi0616-project

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        - BASE_IMAGE=ubuntu:22.04
        - GPU_ENABLED=false
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app/src
      - ./.cdsapirc:/root/.cdsapirc:ro

      # gpu01で共有メモリ不足になったら
      - /dev/shm:/dev/shm  # ホストの共有メモリを直接マウント
      
    # platform: 'linux/amd64' # Apple Silicon Macでx86イメージを強制したい場合のみコメント解除
