# GPU環境用の上書き設定ファイル
# 実行コマンド: docker compose -f compose.yml -f compose.gpu.yml up

services:
  app:
    build:
      # build.argsをGPU用の値で上書き
      args:
        - BASE_IMAGE=nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
        - GPU_ENABLED=true
    # GPUリソースを割り当てるdeployセクションを追加
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]